// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: features_dump.sql

package database

import (
	"context"
	"database/sql"
)

const dumpFeaturesHourPage = `-- name: DumpFeaturesHourPage :many
SELECT
  token_id, ts, ret_1m, ret_5m, vol_1m, avg_vol_5m,
  sigma_5m, zscore_5m, imbalance_top, spread_bps,
  broke_high_15m, broke_low_15m, time_to_resolve_h, signed_flow_1m
FROM market_features
WHERE ts >= $1::timestamptz
  AND ts  < $2::timestamptz
  AND (
    $3::timestamptz IS NULL
    OR (ts, token_id) > ($3::timestamptz,
                         COALESCE($4::text, ''))
  )
ORDER BY ts, token_id
LIMIT $5::int
`

type DumpFeaturesHourPageParams struct {
	TsStart      sql.NullTime   `json:"ts_start"`
	TsEnd        sql.NullTime   `json:"ts_end"`
	AfterTs      sql.NullTime   `json:"after_ts"`
	AfterTokenID sql.NullString `json:"after_token_id"`
	PageLimit    int32          `json:"page_limit"`
}

func (q *Queries) DumpFeaturesHourPage(ctx context.Context, arg DumpFeaturesHourPageParams) ([]MarketFeature, error) {
	rows, err := q.db.QueryContext(ctx, dumpFeaturesHourPage,
		arg.TsStart,
		arg.TsEnd,
		arg.AfterTs,
		arg.AfterTokenID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketFeature{}
	for rows.Next() {
		var i MarketFeature
		if err := rows.Scan(
			&i.TokenID,
			&i.Ts,
			&i.Ret1m,
			&i.Ret5m,
			&i.Vol1m,
			&i.AvgVol5m,
			&i.Sigma5m,
			&i.Zscore5m,
			&i.ImbalanceTop,
			&i.SpreadBps,
			&i.BrokeHigh15m,
			&i.BrokeLow15m,
			&i.TimeToResolveH,
			&i.SignedFlow1m,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oldestUnarchivedFeaturesHour = `-- name: OldestUnarchivedFeaturesHour :one
SELECT date_trunc('hour', m.ts)::timestamptz AS oldest
FROM market_features AS m
WHERE NOT EXISTS (
  SELECT 1
  FROM archive_jobs aj
  WHERE aj.table_name = 'market_features'
    AND aj.status     = 'done'
    AND m.ts >= aj.ts_start AND m.ts < aj.ts_end
)
ORDER BY m.ts
LIMIT 1
`

func (q *Queries) OldestUnarchivedFeaturesHour(ctx context.Context) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, oldestUnarchivedFeaturesHour)
	var oldest sql.NullTime
	err := row.Scan(&oldest)
	return oldest, err
}
