// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: features_temp.sql

package database

import (
	"context"
)

const createUniqueTempMarketFeaturesStage = `-- name: CreateUniqueTempMarketFeaturesStage :one
SELECT create_unique_temp_market_features_stage() AS temp_qualname
`

func (q *Queries) CreateUniqueTempMarketFeaturesStage(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, createUniqueTempMarketFeaturesStage)
	var temp_qualname string
	err := row.Scan(&temp_qualname)
	return temp_qualname, err
}
