// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: features_dump.sql

package database

import (
	"context"
	"database/sql"
)

const dumpFeaturesHour = `-- name: DumpFeaturesHour :many
SELECT
  token_id, ts, ret_1m, ret_5m, vol_1m, avg_vol_5m, sigma_5m, zscore_5m,
  imbalance_top, spread_bps, broke_high_15m, broke_low_15m, time_to_resolve_h, signed_flow_1m
FROM market_features
WHERE ts >= $1::timestamptz
  AND ts  < $2  ::timestamptz
ORDER BY ts, token_id
`

type DumpFeaturesHourParams struct {
	TsStart sql.NullTime `json:"ts_start"`
	TsEnd   sql.NullTime `json:"ts_end"`
}

func (q *Queries) DumpFeaturesHour(ctx context.Context, arg DumpFeaturesHourParams) ([]MarketFeature, error) {
	rows, err := q.db.QueryContext(ctx, dumpFeaturesHour, arg.TsStart, arg.TsEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketFeature{}
	for rows.Next() {
		var i MarketFeature
		if err := rows.Scan(
			&i.TokenID,
			&i.Ts,
			&i.Ret1m,
			&i.Ret5m,
			&i.Vol1m,
			&i.AvgVol5m,
			&i.Sigma5m,
			&i.Zscore5m,
			&i.ImbalanceTop,
			&i.SpreadBps,
			&i.BrokeHigh15m,
			&i.BrokeLow15m,
			&i.TimeToResolveH,
			&i.SignedFlow1m,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oldestUnarchivedFeaturesHour = `-- name: OldestUnarchivedFeaturesHour :one
WITH hourly AS (
  SELECT date_trunc('hour', ts) AS h
  FROM market_features
  GROUP BY 1
)
SELECT MIN(h)::timestamptz AS oldest
FROM hourly
WHERE NOT EXISTS (
  SELECT 1
  FROM archive_jobs aj
  WHERE aj.table_name = 'market_features'
    AND aj.status     = 'done'
    AND h >= aj.ts_start AND h < aj.ts_end
)
`

func (q *Queries) OldestUnarchivedFeaturesHour(ctx context.Context) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, oldestUnarchivedFeaturesHour)
	var oldest sql.NullTime
	err := row.Scan(&oldest)
	return oldest, err
}
