// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: features_merge.sql

package database

import (
	"context"
)

const mergeMarketFeaturesFrom = `-- name: MergeMarketFeaturesFrom :exec
SELECT merge_market_features_from($1::text)
`

func (q *Queries) MergeMarketFeaturesFrom(ctx context.Context, tempTable string) error {
	_, err := q.db.ExecContext(ctx, mergeMarketFeaturesFrom, tempTable)
	return err
}
