// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: features_merge.sql

package database

import (
	"context"
)

const mergeMarketFeaturesStage = `-- name: MergeMarketFeaturesStage :exec
SELECT merge_market_features_stage()
`

func (q *Queries) MergeMarketFeaturesStage(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, mergeMarketFeaturesStage)
	return err
}
