// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: health_metrics.sql

package database

import (
	"context"
	"database/sql"
)

const dbSizePretty = `-- name: DbSizePretty :one
SELECT pg_size_pretty(pg_database_size($1::text))
`

func (q *Queries) DbSizePretty(ctx context.Context, dbname string) (string, error) {
	row := q.db.QueryRowContext(ctx, dbSizePretty, dbname)
	var pg_size_pretty string
	err := row.Scan(&pg_size_pretty)
	return pg_size_pretty, err
}

const getPartitionSpan = `-- name: GetPartitionSpan :one
WITH r AS (
  SELECT poly_partition_span($1) AS t
)
SELECT
  (r.t).partition_count::int4         AS partition_count,
  (r.t).oldest_partition::timestamptz AS oldest_partition,
  (r.t).newest_partition::timestamptz AS newest_partition
FROM r
`

type GetPartitionSpanRow struct {
	PartitionCount  int32        `json:"partition_count"`
	OldestPartition sql.NullTime `json:"oldest_partition"`
	NewestPartition sql.NullTime `json:"newest_partition"`
}

func (q *Queries) GetPartitionSpan(ctx context.Context, pattern string) (GetPartitionSpanRow, error) {
	row := q.db.QueryRowContext(ctx, getPartitionSpan, pattern)
	var i GetPartitionSpanRow
	err := row.Scan(&i.PartitionCount, &i.OldestPartition, &i.NewestPartition)
	return i, err
}

const lastArchiveDoneEnd = `-- name: LastArchiveDoneEnd :one
SELECT MAX(ts_end)::timestamptz
FROM archive_jobs
WHERE table_name = $1
  AND status = 'done'
`

func (q *Queries) LastArchiveDoneEnd(ctx context.Context, tableName string) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, lastArchiveDoneEnd, tableName)
	var column_1 sql.NullTime
	err := row.Scan(&column_1)
	return column_1, err
}

const sumPartitionSizesMB = `-- name: SumPartitionSizesMB :one
SELECT poly_sum_partition_sizes_mb($1) AS total_mb
`

func (q *Queries) SumPartitionSizesMB(ctx context.Context, pattern string) (float64, error) {
	row := q.db.QueryRowContext(ctx, sumPartitionSizesMB, pattern)
	var total_mb float64
	err := row.Scan(&total_mb)
	return total_mb, err
}
