// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: janitor.sql

package database

import (
	"context"
)

const deleteExportedHoursFeatures = `-- name: DeleteExportedHoursFeatures :one
SELECT delete_exported_hours_features($1::text) AS deleted
`

func (q *Queries) DeleteExportedHoursFeatures(ctx context.Context, win string) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteExportedHoursFeatures, win)
	var deleted int64
	err := row.Scan(&deleted)
	return deleted, err
}

const deleteExportedHoursQuotes = `-- name: DeleteExportedHoursQuotes :one
SELECT delete_exported_hours_quotes($1::text) AS deleted
`

// Windowed deletes (rename param to avoid reserved keyword)
func (q *Queries) DeleteExportedHoursQuotes(ctx context.Context, win string) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteExportedHoursQuotes, win)
	var deleted int64
	err := row.Scan(&deleted)
	return deleted, err
}

const deleteExportedHoursTrades = `-- name: DeleteExportedHoursTrades :one
SELECT delete_exported_hours_trades($1::text) AS deleted
`

func (q *Queries) DeleteExportedHoursTrades(ctx context.Context, win string) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteExportedHoursTrades, win)
	var deleted int64
	err := row.Scan(&deleted)
	return deleted, err
}

const dropArchivedMarketFeaturesPartitionsHourly = `-- name: DropArchivedMarketFeaturesPartitionsHourly :one
SELECT drop_archived_market_features_partitions_hourly($1::int) AS dropped
`

func (q *Queries) DropArchivedMarketFeaturesPartitionsHourly(ctx context.Context, keepHours int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, dropArchivedMarketFeaturesPartitionsHourly, keepHours)
	var dropped int32
	err := row.Scan(&dropped)
	return dropped, err
}

const dropArchivedMarketQuotesPartitionsHourly = `-- name: DropArchivedMarketQuotesPartitionsHourly :one
SELECT drop_archived_market_quotes_partitions_hourly($1::int) AS dropped
`

// Drop archived partitions
func (q *Queries) DropArchivedMarketQuotesPartitionsHourly(ctx context.Context, keepHours int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, dropArchivedMarketQuotesPartitionsHourly, keepHours)
	var dropped int32
	err := row.Scan(&dropped)
	return dropped, err
}

const dropArchivedMarketTradesPartitionsHourly = `-- name: DropArchivedMarketTradesPartitionsHourly :one
SELECT drop_archived_market_trades_partitions_hourly($1::int) AS dropped
`

func (q *Queries) DropArchivedMarketTradesPartitionsHourly(ctx context.Context, keepHours int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, dropArchivedMarketTradesPartitionsHourly, keepHours)
	var dropped int32
	err := row.Scan(&dropped)
	return dropped, err
}

const emergencyDeleteFeatures = `-- name: EmergencyDeleteFeatures :one
WITH doomed AS (
  SELECT token_id, ts
  FROM market_features
  WHERE ts < now() - ($1::text)::interval
  ORDER BY ts ASC, token_id ASC
  LIMIT $2::int
),
del AS (
  DELETE FROM market_features f
  USING doomed d
  WHERE f.token_id = d.token_id
    AND f.ts       = d.ts
  RETURNING 1
)
SELECT COALESCE(count(*), 0)::bigint AS deleted
`

type EmergencyDeleteFeaturesParams struct {
	KeepText string `json:"keep_text"`
	Batch    int32  `json:"batch"`
}

func (q *Queries) EmergencyDeleteFeatures(ctx context.Context, arg EmergencyDeleteFeaturesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, emergencyDeleteFeatures, arg.KeepText, arg.Batch)
	var deleted int64
	err := row.Scan(&deleted)
	return deleted, err
}

const emergencyDeleteQuotes = `-- name: EmergencyDeleteQuotes :one
WITH doomed AS (
  SELECT id
  FROM market_quotes
  WHERE ts < now() - ($1::text)::interval
  ORDER BY ts ASC
  LIMIT $2::int
),
del AS (
  DELETE FROM market_quotes q
  USING doomed d
  WHERE q.id = d.id
  RETURNING 1
)
SELECT COALESCE(count(*), 0)::bigint AS deleted
`

type EmergencyDeleteQuotesParams struct {
	KeepText string `json:"keep_text"`
	Batch    int32  `json:"batch"`
}

// Emergency deletes (batched)
func (q *Queries) EmergencyDeleteQuotes(ctx context.Context, arg EmergencyDeleteQuotesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, emergencyDeleteQuotes, arg.KeepText, arg.Batch)
	var deleted int64
	err := row.Scan(&deleted)
	return deleted, err
}

const emergencyDeleteTrades = `-- name: EmergencyDeleteTrades :one
WITH doomed AS (
  SELECT id
  FROM market_trades
  WHERE ts < now() - ($1::text)::interval
  ORDER BY ts ASC
  LIMIT $2::int
),
del AS (
  DELETE FROM market_trades t
  USING doomed d
  WHERE t.id = d.id
  RETURNING 1
)
SELECT COALESCE(count(*), 0)::bigint AS deleted
`

type EmergencyDeleteTradesParams struct {
	KeepText string `json:"keep_text"`
	Batch    int32  `json:"batch"`
}

func (q *Queries) EmergencyDeleteTrades(ctx context.Context, arg EmergencyDeleteTradesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, emergencyDeleteTrades, arg.KeepText, arg.Batch)
	var deleted int64
	err := row.Scan(&deleted)
	return deleted, err
}

const ensureFeaturesPartitionsHourly = `-- name: EnsureFeaturesPartitionsHourly :exec
SELECT ensure_features_partitions_hourly($1::int, $2::int)
`

type EnsureFeaturesPartitionsHourlyParams struct {
	Back int32 `json:"back"`
	Fwd  int32 `json:"fwd"`
}

func (q *Queries) EnsureFeaturesPartitionsHourly(ctx context.Context, arg EnsureFeaturesPartitionsHourlyParams) error {
	_, err := q.db.ExecContext(ctx, ensureFeaturesPartitionsHourly, arg.Back, arg.Fwd)
	return err
}

const ensureQuotesPartitionsHourly = `-- name: EnsureQuotesPartitionsHourly :exec
SELECT ensure_quotes_partitions_hourly($1::int, $2::int)
`

type EnsureQuotesPartitionsHourlyParams struct {
	Back int32 `json:"back"`
	Fwd  int32 `json:"fwd"`
}

// Ensure partitions (hourly)
func (q *Queries) EnsureQuotesPartitionsHourly(ctx context.Context, arg EnsureQuotesPartitionsHourlyParams) error {
	_, err := q.db.ExecContext(ctx, ensureQuotesPartitionsHourly, arg.Back, arg.Fwd)
	return err
}

const ensureTradesPartitionsHourly = `-- name: EnsureTradesPartitionsHourly :exec
SELECT ensure_trades_partitions_hourly($1::int, $2::int)
`

type EnsureTradesPartitionsHourlyParams struct {
	Back int32 `json:"back"`
	Fwd  int32 `json:"fwd"`
}

func (q *Queries) EnsureTradesPartitionsHourly(ctx context.Context, arg EnsureTradesPartitionsHourlyParams) error {
	_, err := q.db.ExecContext(ctx, ensureTradesPartitionsHourly, arg.Back, arg.Fwd)
	return err
}

const pgCheckpoint = `-- name: PgCheckpoint :exec
CHECKPOINT
`

func (q *Queries) PgCheckpoint(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, pgCheckpoint)
	return err
}

const pgSwitchWal = `-- name: PgSwitchWal :one
SELECT pg_switch_wal()::text AS lsn
`

func (q *Queries) PgSwitchWal(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, pgSwitchWal)
	var lsn string
	err := row.Scan(&lsn)
	return lsn, err
}

const vacuumFeatures = `-- name: VacuumFeatures :exec
VACUUM (ANALYZE) market_features
`

func (q *Queries) VacuumFeatures(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, vacuumFeatures)
	return err
}

const vacuumQuotes = `-- name: VacuumQuotes :exec
VACUUM (ANALYZE) market_quotes
`

// Optional VACUUM helpers
func (q *Queries) VacuumQuotes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, vacuumQuotes)
	return err
}

const vacuumTrades = `-- name: VacuumTrades :exec
VACUUM (ANALYZE) market_trades
`

func (q *Queries) VacuumTrades(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, vacuumTrades)
	return err
}
