// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"encoding/json"

	"github.com/sqlc-dev/pqtype"
)

type Market struct {
	ID        int32          `json:"id"`
	TokenID   string         `json:"token_id"`
	Slug      sql.NullString `json:"slug"`
	Question  sql.NullString `json:"question"`
	Outcome   sql.NullString `json:"outcome"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type MarketEvent struct {
	ID         int32                 `json:"id"`
	TokenID    string                `json:"token_id"`
	EventType  sql.NullString        `json:"event_type"`
	OldValue   sql.NullString        `json:"old_value"`
	NewValue   sql.NullString        `json:"new_value"`
	Metadata   pqtype.NullRawMessage `json:"metadata"`
	DetectedAt sql.NullTime          `json:"detected_at"`
}

type MarketScan struct {
	ID            int32                 `json:"id"`
	TokenID       string                `json:"token_id"`
	EventID       sql.NullString        `json:"event_id"`
	Slug          sql.NullString        `json:"slug"`
	Question      sql.NullString        `json:"question"`
	LastPrice     sql.NullString        `json:"last_price"`
	LastVolume    sql.NullString        `json:"last_volume"`
	Liquidity     sql.NullString        `json:"liquidity"`
	LastScannedAt sql.NullTime          `json:"last_scanned_at"`
	Price24hAgo   sql.NullString        `json:"price_24h_ago"`
	Volume24hAgo  sql.NullString        `json:"volume_24h_ago"`
	ScanCount     sql.NullInt64         `json:"scan_count"`
	IsActive      sql.NullBool          `json:"is_active"`
	Metadata      pqtype.NullRawMessage `json:"metadata"`
	CreatedAt     sql.NullTime          `json:"created_at"`
	UpdatedAt     sql.NullTime          `json:"updated_at"`
}

type MarketSignal struct {
	ID           int32          `json:"id"`
	SessionID    sql.NullInt32  `json:"session_id"`
	TokenID      string         `json:"token_id"`
	SignalType   string         `json:"signal_type"`
	Timestamp    sql.NullTime   `json:"timestamp"`
	BestBid      sql.NullString `json:"best_bid"`
	BestAsk      sql.NullString `json:"best_ask"`
	BidLiquidity sql.NullString `json:"bid_liquidity"`
	AskLiquidity sql.NullString `json:"ask_liquidity"`
	ActionReason sql.NullString `json:"action_reason"`
	Confidence   sql.NullString `json:"confidence"`
}

type PaperOrder struct {
	ID        int32          `json:"id"`
	SessionID sql.NullInt32  `json:"session_id"`
	SignalID  sql.NullInt32  `json:"signal_id"`
	TokenID   string         `json:"token_id"`
	Side      string         `json:"side"`
	Price     string         `json:"price"`
	Size      string         `json:"size"`
	Status    sql.NullString `json:"status"`
	CreatedAt sql.NullTime   `json:"created_at"`
	FilledAt  sql.NullTime   `json:"filled_at"`
}

type PaperPosition struct {
	ID            int32          `json:"id"`
	SessionID     sql.NullInt32  `json:"session_id"`
	TokenID       string         `json:"token_id"`
	Shares        string         `json:"shares"`
	AvgEntryPrice sql.NullString `json:"avg_entry_price"`
	CurrentPrice  sql.NullString `json:"current_price"`
	UnrealizedPnl sql.NullString `json:"unrealized_pnl"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type Strategy struct {
	ID             int32           `json:"id"`
	Name           string          `json:"name"`
	Config         json.RawMessage `json:"config"`
	InitialBalance sql.NullString  `json:"initial_balance"`
	Active         sql.NullBool    `json:"active"`
	CreatedAt      sql.NullTime    `json:"created_at"`
}

type TradingSession struct {
	ID             int32          `json:"id"`
	StrategyID     sql.NullInt32  `json:"strategy_id"`
	StartBalance   sql.NullString `json:"start_balance"`
	CurrentBalance sql.NullString `json:"current_balance"`
	StartedAt      sql.NullTime   `json:"started_at"`
	EndedAt        sql.NullTime   `json:"ended_at"`
}
