// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (TradingSession, error)
	CreateStrategy(ctx context.Context, arg CreateStrategyParams) (Strategy, error)
	EndSession(ctx context.Context, id int32) error
	GetActiveMarkets(ctx context.Context) ([]Market, error)
	GetActiveSession(ctx context.Context, strategyID sql.NullInt32) (TradingSession, error)
	GetMarketByTokenID(ctx context.Context, tokenID string) (Market, error)
	GetRecentSignals(ctx context.Context, arg GetRecentSignalsParams) ([]MarketSignal, error)
	GetSignalsByType(ctx context.Context, arg GetSignalsByTypeParams) ([]MarketSignal, error)
	RecordSignal(ctx context.Context, arg RecordSignalParams) (MarketSignal, error)
	UpdateSessionBalance(ctx context.Context, arg UpdateSessionBalanceParams) error
	UpsertMarket(ctx context.Context, arg UpsertMarketParams) (Market, error)
}

var _ Querier = (*Queries)(nil)
