// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quotes_dump.sql

package database

import (
	"context"
	"database/sql"
)

const dumpQuotesHour = `-- name: DumpQuotesHour :many
SELECT token_id, ts, best_bid, best_ask, bid_size1, ask_size1, spread_bps, mid
FROM market_quotes
WHERE ts >= $1::timestamptz
  AND ts  < $2  ::timestamptz
ORDER BY ts, id
`

type DumpQuotesHourParams struct {
	TsStart sql.NullTime `json:"ts_start"`
	TsEnd   sql.NullTime `json:"ts_end"`
}

type DumpQuotesHourRow struct {
	TokenID   string          `json:"token_id"`
	Ts        sql.NullTime    `json:"ts"`
	BestBid   sql.NullFloat64 `json:"best_bid"`
	BestAsk   sql.NullFloat64 `json:"best_ask"`
	BidSize1  sql.NullFloat64 `json:"bid_size1"`
	AskSize1  sql.NullFloat64 `json:"ask_size1"`
	SpreadBps sql.NullFloat64 `json:"spread_bps"`
	Mid       sql.NullFloat64 `json:"mid"`
}

func (q *Queries) DumpQuotesHour(ctx context.Context, arg DumpQuotesHourParams) ([]DumpQuotesHourRow, error) {
	rows, err := q.db.QueryContext(ctx, dumpQuotesHour, arg.TsStart, arg.TsEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DumpQuotesHourRow{}
	for rows.Next() {
		var i DumpQuotesHourRow
		if err := rows.Scan(
			&i.TokenID,
			&i.Ts,
			&i.BestBid,
			&i.BestAsk,
			&i.BidSize1,
			&i.AskSize1,
			&i.SpreadBps,
			&i.Mid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oldestUnarchivedQuotesHour = `-- name: OldestUnarchivedQuotesHour :one
SELECT date_trunc('hour', m.ts)::timestamptz AS oldest
FROM market_quotes AS m
WHERE NOT EXISTS (
  SELECT 1
  FROM archive_jobs aj
  WHERE aj.table_name = 'market_quotes'
    AND aj.status     = 'done'
    AND m.ts >= aj.ts_start AND m.ts < aj.ts_end
)
ORDER BY m.ts
LIMIT 1
`

func (q *Queries) OldestUnarchivedQuotesHour(ctx context.Context) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, oldestUnarchivedQuotesHour)
	var oldest sql.NullTime
	err := row.Scan(&oldest)
	return oldest, err
}
