// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trades_dump.sql

package database

import (
	"context"
	"database/sql"
)

const dumpTradesHour = `-- name: DumpTradesHour :many
SELECT token_id, ts, price, size, aggressor, trade_id
FROM market_trades
WHERE ts >= $1::timestamptz
  AND ts  < $2  ::timestamptz
ORDER BY ts, id
`

type DumpTradesHourParams struct {
	TsStart sql.NullTime `json:"ts_start"`
	TsEnd   sql.NullTime `json:"ts_end"`
}

type DumpTradesHourRow struct {
	TokenID   string         `json:"token_id"`
	Ts        sql.NullTime   `json:"ts"`
	Price     float64        `json:"price"`
	Size      float64        `json:"size"`
	Aggressor sql.NullString `json:"aggressor"`
	TradeID   sql.NullString `json:"trade_id"`
}

func (q *Queries) DumpTradesHour(ctx context.Context, arg DumpTradesHourParams) ([]DumpTradesHourRow, error) {
	rows, err := q.db.QueryContext(ctx, dumpTradesHour, arg.TsStart, arg.TsEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DumpTradesHourRow{}
	for rows.Next() {
		var i DumpTradesHourRow
		if err := rows.Scan(
			&i.TokenID,
			&i.Ts,
			&i.Price,
			&i.Size,
			&i.Aggressor,
			&i.TradeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oldestUnarchivedTradesHour = `-- name: OldestUnarchivedTradesHour :one
WITH hourly_data AS (
  SELECT date_trunc('hour', ts) AS hour
  FROM market_trades
  GROUP BY 1
)
SELECT CAST(MIN(hour) AS timestamptz) AS oldest
`

func (q *Queries) OldestUnarchivedTradesHour(ctx context.Context) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, oldestUnarchivedTradesHour)
	var oldest sql.NullTime
	err := row.Scan(&oldest)
	return oldest, err
}
