// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trades_dump.sql

package database

import (
	"context"
	"database/sql"
)

const dumpTradesHourPage = `-- name: DumpTradesHourPage :many
SELECT token_id, ts, price, size, aggressor, trade_id, id
FROM market_trades
WHERE ts >= $1::timestamptz
  AND ts  < $2::timestamptz
  AND (
    $3::timestamptz IS NULL
    OR (ts, id) > ($3::timestamptz, $4::bigint)
  )
ORDER BY ts, id
LIMIT $5::int
`

type DumpTradesHourPageParams struct {
	TsStart   sql.NullTime  `json:"ts_start"`
	TsEnd     sql.NullTime  `json:"ts_end"`
	AfterTs   sql.NullTime  `json:"after_ts"`
	AfterID   sql.NullInt64 `json:"after_id"`
	PageLimit int32         `json:"page_limit"`
}

type DumpTradesHourPageRow struct {
	TokenID   string         `json:"token_id"`
	Ts        sql.NullTime   `json:"ts"`
	Price     float64        `json:"price"`
	Size      float64        `json:"size"`
	Aggressor sql.NullString `json:"aggressor"`
	TradeID   sql.NullString `json:"trade_id"`
	ID        int64          `json:"id"`
}

func (q *Queries) DumpTradesHourPage(ctx context.Context, arg DumpTradesHourPageParams) ([]DumpTradesHourPageRow, error) {
	rows, err := q.db.QueryContext(ctx, dumpTradesHourPage,
		arg.TsStart,
		arg.TsEnd,
		arg.AfterTs,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DumpTradesHourPageRow{}
	for rows.Next() {
		var i DumpTradesHourPageRow
		if err := rows.Scan(
			&i.TokenID,
			&i.Ts,
			&i.Price,
			&i.Size,
			&i.Aggressor,
			&i.TradeID,
			&i.ID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oldestUnarchivedTradesHour = `-- name: OldestUnarchivedTradesHour :one
SELECT date_trunc('hour', m.ts)::timestamptz AS oldest
FROM market_trades AS m
WHERE NOT EXISTS (
  SELECT 1
  FROM archive_jobs aj
  WHERE aj.table_name = 'market_trades'
    AND aj.status     = 'done'
    AND m.ts >= aj.ts_start AND m.ts < aj.ts_end
)
ORDER BY m.ts
LIMIT 1
`

func (q *Queries) OldestUnarchivedTradesHour(ctx context.Context) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, oldestUnarchivedTradesHour)
	var oldest sql.NullTime
	err := row.Scan(&oldest)
	return oldest, err
}
