x-logging: &default-logging
  driver: json-file
  options:
    max-size: "50m"
    max-file: "3"

services:
  postgres:
    logging: *default-logging
    image: postgres:14
    shm_size: "1g"
    command:
      - postgres
      - -c
      - wal_compression=on
      - -c
      - max_wal_size=1GB
      - -c
      - min_wal_size=256MB
      - -c
      - shared_buffers=256MB
      - -c
      - checkpoint_timeout=15min
      - -c
      - checkpoint_completion_target=0.9
      - -c
      - autovacuum_vacuum_cost_limit=1000
      - -c
      - autovacuum_max_workers=2
      - -c
      - autovacuum_naptime=1min
      - -c
      - effective_io_concurrency=50
      - -c
      - maintenance_work_mem=256MB
    environment:
      POSTGRES_DB: polymarket_dev
      POSTGRES_USER: a8garber
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U a8garber -d polymarket_dev || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s

  migrator:
    logging: *default-logging
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./sql/migrations:/migrations:ro
    command: ["goose", "-dir", "/migrations", "postgres", "postgresql://a8garber:${POSTGRES_PASSWORD}@postgres:5432/polymarket_dev?sslmode=disable", "up"]
    restart: "no"

  gatherer:
    logging: *default-logging
    build: .
    depends_on:
      migrator:
        condition: service_completed_successfully
      healthmonitor:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://a8garber:${POSTGRES_PASSWORD}@postgres:5432/polymarket_dev?sslmode=disable
      API_KEY: ${API_KEY}
      RUN_TYPE: prod
      GATHERER_DEBUG_ADDR: ":6060"
      GATHERER_USE_WS: ${GATHERER_USE_WS:-true}
      GATHERER_WS_URL: ${GATHERER_WS_URL:-wss://ws-subscriptions-clob.polymarket.com/ws/market}
      GATHERER_SCAN_INTERVAL: ${GATHERER_SCAN_INTERVAL:-30s}
      POLY_WS_DEBUG: ${POLY_WS_DEBUG:-1}
      POLY_WS_LOG_UNKNOWN: ${POLY_WS_LOG_UNKNOWN:-1}
    ports:
      - "6060:6060"
    command: ["/usr/local/bin/gatherer"]
    volumes:
      - retention_policy:/tmp:ro
    restart: unless-stopped

  api:
    logging: *default-logging
    build: .
    depends_on:
      migrator:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: postgresql://a8garber:${POSTGRES_PASSWORD}@postgres:5432/polymarket_dev?sslmode=disable
      API_KEY: ${API_KEY}
      API_PORT: 8080
    command: ["/usr/local/bin/api"]
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://localhost:8080/health >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 6
    restart: unless-stopped

  strategies:
    logging: *default-logging
    build: .
    depends_on:
      migrator:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: postgresql://a8garber:${POSTGRES_PASSWORD}@postgres:5432/polymarket_dev?sslmode=disable
      RUN_TYPE: prod
    command: ["/app/orchestrator", "--binary", "--run", "prod"]
    volumes:
      - ./configs:/app/configs:ro
    restart: unless-stopped
  
  healthmonitor:
    logging: *default-logging
    build: .
    environment:
      DATABASE_URL: postgresql://a8garber:${POSTGRES_PASSWORD}@postgres:5432/polymarket_dev?sslmode=disable
    command: ["/usr/local/bin/healthmonitor", "-target", "70", "-interval", "30s"]
    volumes:
      - retention_policy:/tmp
    restart: unless-stopped
    depends_on:
      migrator:
        condition: service_completed_successfully

  archiver:
    build: .
    environment:
      DATABASE_URL: postgresql://a8garber:${POSTGRES_PASSWORD}@postgres:5432/polymarket_dev?sslmode=disable
      ARCHIVE_S3_BUCKET: ${ARCHIVE_S3_BUCKET}
      AWS_REGION: ${AWS_REGION}
      TABLES: ${ARCHIVER_TABLES:-market_features,market_trades,market_quotes}
    command: ["/usr/local/bin/archiver",
              "-tables", "${TABLES}",
              "-concurrency", "3",
              "-backfill"]
    volumes:
      - retention_policy:/tmp:ro
    depends_on:
      migrator:
        condition: service_completed_successfully
      healthmonitor:
        condition: service_started
    restart: unless-stopped

  janitor:
    logging: *default-logging
    build: .
    depends_on:
      migrator:
        condition: service_completed_successfully
      healthmonitor:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://a8garber:${POSTGRES_PASSWORD}@postgres:5432/polymarket_dev?sslmode=disable
    command: ["/usr/local/bin/janitor"]
    volumes:
      - retention_policy:/tmp:ro
    restart: unless-stopped

volumes:
  postgres_data:
  retention_policy: