version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: polymarket_dev
      POSTGRES_USER: a8garber
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./sql/schemas/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      DATABASE_URL: postgresql://a8garber:${POSTGRES_PASSWORD}@postgres:5432/polymarket_dev?sslmode=disable
      PRIVATE_KEY: ${PRIVATE_KEY}
      RUN_TYPE: test 
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./configs:/app/configs:ro
    restart: unless-stopped
  
  api:
    build: .
    command: ["/usr/local/bin/api"]
    environment:
      DATABASE_URL: postgresql://a8garber:${POSTGRES_PASSWORD}@postgres:5432/polymarket_dev?sslmode=disable
      API_KEY: ${API_KEY}
      API_PORT: 8080
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data: